name: Change
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
jobs:
  dotnet-validate:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-validate.yml@master
    with:
      solution_file: FreeCompanyRegister.sln
      pack: false