name: Release
on:
  release:
    types: [published]
jobs:
  dotnet-release:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-release.yml@master
    with:
      solution_file: FreeCompanyRegister.sln
      project_folder: FreeCompanyRegister
      target_framework: net8.0
      zip_prefix: FreeCompanyRegister
      dotnet_version: 8